version: '3'
services:
  nginxproxy:
    restart: on-failure
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "80:80"

  boat:
    restart: always
    privileged: true
    volumes:
      - /dev/mem:/dev/mem
      - ./public:/go/src/public
    ports:
      - "8000:8000"
    build:
      context: ./go
    
  streamer:
    restart: on-failure
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /dev:/dev
    image: mhamanaka/rpi-mjpg-streamer-uvc:0.1
